### ISSUE TITLE
Typo in Docker run commands - `--device /dev/net/run` instead of `--device /dev/net/tun`

### ISSUE THREAD

**Issue by debemdeboas** [qdm12/gluetun-wiki#115]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md

### What's incorrect?

There appears to be a typo in both OpenVPN and Wireguard Docker configurations where the device path is incorrectly specified as `/dev/net/run` instead of the correct `/dev/net/tun`.
The Docker Compose configuration is correct.

**Comment by africabushpilot** [comment]
Same here, for both docker run examples.

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md

**Comment by fastily** [comment]
looks like this was fixed in bb23197.  Also dupe of #107.

**Comment by debemdeboas** [comment]
yup. fixed
