### ISSUE TITLE
Where to get privatekey & publickey for custom Wireguard connections from?

### ISSUE THREAD

**Issue by legraml** [qdm12/gluetun-wiki#12]
Hi there,

I can't seem to find any info about how to generate publickey and privatekey. Would I have to do so outside docker / gluetun?

**Comment by Quarkz14** [comment]
Hey, your VPN provider should have config generators where they generate the public and private key.

**Comment by qdm12** [comment]
As @Quarkz14 says, or reach out to your vpn provider. Not all providers support Wireguard either.
