### ISSUE TITLE
Feature requests: astrill vpn + shadowsocks client

### ISSUE THREAD

**Issue by helge123** [qdm12/gluetun-wiki#13]
Hello,
I just have seen your project and I really like it. I'm just wondering if it is possible to add a config for astrill Vpn.
I'm also running a shadowsocksr server and I would like to ask if it might be possible to connect from my unraid to this serve
Means can I use your project as an client as well. I just checked and for the Shadowsocks client, I'm using on my phone there are are several additional "fields" to fill in such a serve, remote port, local port encrypt method and protocol to connect to thia server. I believe you can see from my message I live in a country with a famous "wall".
Thank you

**Comment by qdm12** [comment]
> I'm just wondering if it is possible to add a config for astrill Vpn.

Please create an issue using [this template](https://github.com/qdm12/gluetun/issues/new?assignees=&labels=%3Abulb%3A+New+provider&projects=&template=provider.md&title=VPN+provider+support%3A+NAME+OF+THE+PROVIDER)

> I'm also running a shadowsocksr server and I would like to ask if it might be possible to connect from my unraid to this serve

You want to connect to a remote Shadowsocks server from Gluetun right? Gluetun right now does not have a shadowsocks client implementation, but feel free to open a [new feature request issue](https://github.com/qdm12/gluetun/issues/new?assignees=&labels=%3Abulb%3A+feature+request&projects=&template=feature_request.yml&title=Feature+request%3A+). So is your wall only blocking Wireguard and Openvpn, not Shadowsocks? That sounds a bit silly to me 😸
