### ISSUE TITLE
ping within the gluetun network stack

### ISSUE THREAD

**Issue by shuntera** [qdm12/gluetun-wiki#19]
Should i be able to ping around the various containers under the network stack for all the service/containers in the same docker compose file.

eg if I have the sonarr service running under gluetun in the same docker-compose file should I be able to perform:

docker exec -it gluetun ping sonarr

and get a result?

all I get right now is "ping: bad address 'sonarr'"

**Comment by JermellB** [comment]
Funny enough. This is why I integrated traefik into my stack.
Realized that I couldn't do this.
Most likely a me problem though, I'm not a networking guy.
