### ISSUE TITLE
How to run multiple gluetun instances ?

### ISSUE THREAD

**Issue by vnghia** [qdm12/gluetun-wiki#23]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/multiple-gluetun.md

### What's missing?

In this doc, it says that we can run a shared DNS server for multiple gluetun instances. However, I am unable to find out how to point these instances to that server.

**Comment by qdm12** [comment]
See the DNS options page. Disable DNS over TLS (`DOT=off`) and set the dns plaintext address to your Docker-network-local DNS server container IP address (for example 10.0.0.16).
