### ISSUE TITLE
Any way to add manual DNS?

### ISSUE THREAD

**Issue by iNaiks** [qdm12/gluetun-wiki#24]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/wireguard.md

### What's missing?

No way to add manual DNS for use other DNS

Thanks Nico

**Comment by qdm12** [comment]
This is for the wiki only, search for an issue on the Gluetun repository instead 😉 
You can specify a DNS (over VPN but in plaintext only for now), see the DNS options page https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/dns.md
