### ISSUE TITLE
airvpn config

### ISSUE THREAD

**Issue by EricBettanin** [qdm12/gluetun-wiki#28]
remove IPv6 from ### Wireguard config

add these lines in the fireguard section
You can get the data you need from the Config Generator in the AirVPN Client Area. Gluetun does not support IPv6 so only copy the IPv4 address into the `WIREGUARD_ADDRESSES` variable.

here is the modified file
[airvpn.md](https://github.com/qdm12/gluetun-wiki/files/13646823/airvpn.md)

**Comment by qdm12** [comment]
Actually now Gluetun supports IPv6 (depending on host/router/docker setup)

**Comment by qdm12** [comment]
Warning added in 04513d4ec6f39ff4d3ee2ed550131750ea9d1cf5
