### ISSUE TITLE
Private Internet Access isn't being recognized by gluetun

### ISSUE THREAD

**Issue by trogdoor17** [qdm12/gluetun-wiki#30]
Hi all,

This is my first time posting to any Github community, but I think I found a bug and wanted to just report in. I was trying to install qbittorrent-gluetun, and this error kept coming back:

>ERROR updater settings: VPN provider name is not valid: value is not one of the possible choices: vpn_service_provider=private internet access must be one of airvpn, cyberghost, expressvpn, fastestvpn, hidemyass, ipvanish, ivpn, mullvad, nordvpn, perfect privacy, privado, private internet access, privatevpn, protonvpn, purevpn, slickvpn, surfshark, torguard, vpnsecure, vpn unlimited, vyprvpn, wevpn or windscribe

You can see that private internet access (PIA) is not valid, but it is also one of the possible choices. Is there a workaround for this, or is there something I'm missing?

**Comment by fastily** [comment]
post your config, compose file, and/or whatever command you're running

**Comment by Kieros** [comment]
I have no problems with PIA
- VPN_SERVICE_PROVIDER= 'private internet access'

**Comment by qdm12** [comment]
Your config is wrong you probably set `VPN_SERVICE_PROVIDER=vpn_service_provider=private internet access`.

Anyway this is irrelevant to the wiki so closing this.
