### ISSUE TITLE
Mention that control server OpenVPN endpoint also works for Wireguard

### ISSUE THREAD

**Issue by fastily** [qdm12/gluetun-wiki#31]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/29e3dee5024d82218e3f170b32f027102ff84aab/setup/advanced/control-server.md

### What's missing?

Basically the title.  I discovered that the `/v1/openvpn/*` endpoints also work for Wireguard.  This should probably be documented (assuming it is intentional).

**Comment by qdm12** [comment]
Indeed, fixed in 05ee640762d00b29a966d7a7d1090b24790bc70b Thanks!
