### ISSUE TITLE
Adding pia wireguard to wiki

### ISSUE THREAD

**Issue by Kieros** [qdm12/gluetun-wiki#35]
Not sure where to post this. But I found a rather easy way to setup PIA wireguard with help of the github below by kilegrantlucas.
Via the link below I was able to easely pull off a PIA-wg.conf file.
https://pkg.go.dev/github.com/kylegrantlucas/pia-wg-config#section-readme

Perhaps there can be a writeup for PIA wireguard in the wiki for those interested?
- VPN_SERVICE_PROVIDER=custom
- VPN_TYPE=wireguard
- VPN_ENDPOINT_IP=1.2.3.4
- VPN_ENDPOINT_PORT=51820
- WIREGUARD_PUBLIC_KEY=wAUaJMhAq3NFutLHIdF8AN0B5WG8RndfQKLPTEDHal0=
- WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
- WIREGUARD_ADDRESSES=10.64.222.21/32

It can either be done by entering the enviromental variables from the conf fill required by following the link above.
Or... you can also bind mount this wireguard configuration file (ini format) to /gluetun/wireguard/wg0.conf.

**Comment by Srijal97** [comment]
Thank you! Is it possible to setup port forwarding with this?

**Comment by xtinct101** [comment]
seconded. is there a way to add port forwarding with this?

**Comment by Kieros** [comment]
Haven't tried it but perhaps with
PIA_PF=true

**Comment by xtinct101** [comment]
doesnt seem to do anything...

**Comment by Kieros** [comment]
https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/port-forwarding.md

Add environments

**Comment by xtinct101** [comment]
yeah I've tried those. when using VPN_PORT_FORWARDING=on, gluetun states that it cannot be used with "custom" service provider.

**Comment by qdm12** [comment]
@Kieros Thanks, that's a great tool and I may even incorporate some of its code in Gluetun later on. I've documented it in 78b457bf66e02769de0d0fd96961b5c32f1a330f thanks!

@Srijal97 @xtinct101 @Kieros For port forwarding with Wireguard custom provider, subscribe to issue https://github.com/qdm12/gluetun/issues/2320 it's work-in-progress. I'm hiding your comments as off topic in this issue.

**Comment by sphoenixp** [comment]
@Kieros still not able to configure this. i dont understand where to get this ip port and addresses.
