### ISSUE TITLE
PIA Port Forwarding

### ISSUE THREAD

**Issue by david007co** [qdm12/gluetun-wiki#36]
When I set the env variable:
VPN_PORT_FORWARDING =  on

I get this error in the Gluetun logs:
INFO [port forwarding] port forwarded is 0

Is there any way to fix that issue?  I noticed PIA has this scripts available for port forwarding:
https://helpdesk.privateinternetaccess.com/kb/articles/manual-connection-and-port-forwarding-scripts-for-linux

Thank you,

**Comment by anorth2** [comment]
+1   also affected

**Comment by david007co** [comment]
> +1 also affected

UPDATE:  Actually I found a solution. Port forwarding is working for me.

You need to make sure that you select a region that supports port-forwarding.   

If you want to discover what regions support port-forwarding, this command will pull that info from PIA's API:

`$ curl -s https://serverlist.piaservers.net/vpninfo/servers/v6 | head -n1 | jq -r '.regions | .[] | select(.port_forward) | .name' | sort`

Otherwise, here are the supported regions as of today:
Albania
Algeria
Andorra
Argentina
Armenia
AU Adelaide
AU Brisbane
AU Melbourne
AU Perth
Australia Streaming Optimized
Austria
AU Sydney
Bahamas
Bangladesh
Belgium
Bolivia
Bosnia and Herzegovina
Brazil
Bulgaria
Cambodia
CA Montreal
CA Ontario
CA Toronto
CA Vancouver
Chile
China
Colombia
Costa Rica
Croatia
Cyprus
Czech Republic
DE Berlin
DE Frankfurt
DK Copenhagen
DK Streaming Optimized
Ecuador
Egypt
ES Madrid
Estonia
ES Valencia
FI Helsinki
FI Streaming Optimized
France
Georgia
Greece
Greenland
Guatemala
Hong Kong
Hungary
Iceland
India
Indonesia
Ireland
Isle of Man
Israel
IT Milano
IT Streaming Optimized
JP Streaming Optimized
JP Tokyo
Kazakhstan
Latvia
Liechtenstein
Lithuania
Luxembourg
Macao
Malaysia
Malta
Mexico
Moldova
Monaco
Mongolia
Montenegro
Morocco
Nepal
Netherlands
New Zealand
Nigeria
North Macedonia
Norway
Panama
Peru
Philippines
Poland
Portugal
Qatar
Romania
Saudi Arabia
Serbia
SE Stockholm
SE Streaming Optimized
Singapore
Slovakia
Slovenia
South Africa
South Korea
Sri Lanka
Switzerland
Taiwan
Turkey
UK London
UK Manchester
Ukraine
UK Southampton
UK Streaming Optimized
United Arab Emirates
Uruguay
Venezuela
Vietnam

**Comment by david007co** [comment]
> +1 also affected

UPDATE:  Actually I found a solution. Port forwarding is working for me.

You need to make sure that you select a region that supports port-forwarding.   

If you want to discover what regions support port-forwarding, this command will pull that info from PIA's API:

`$ curl -s https://serverlist.piaservers.net/vpninfo/servers/v6 | head -n1 | jq -r '.regions | .[] | select(.port_forward) | .name' | sort`

Otherwise, here are the supported regions as of today:
Albania
Algeria
Andorra
Argentina
Armenia
AU Adelaide
AU Brisbane
AU Melbourne
AU Perth
Australia Streaming Optimized
Austria
AU Sydney
Bahamas
Bangladesh
Belgium
Bolivia
Bosnia and Herzegovina
Brazil
Bulgaria
Cambodia
CA Montreal
CA Ontario
CA Toronto
CA Vancouver
Chile
China
Colombia
Costa Rica
Croatia
Cyprus
Czech Republic
DE Berlin
DE Frankfurt
DK Copenhagen
DK Streaming Optimized
Ecuador
Egypt
ES Madrid
Estonia
ES Valencia
FI Helsinki
FI Streaming Optimized
France
Georgia
Greece
Greenland
Guatemala
Hong Kong
Hungary
Iceland
India
Indonesia
Ireland
Isle of Man
Israel
IT Milano
IT Streaming Optimized
JP Streaming Optimized
JP Tokyo
Kazakhstan
Latvia
Liechtenstein
Lithuania
Luxembourg
Macao
Malaysia
Malta
Mexico
Moldova
Monaco
Mongolia
Montenegro
Morocco
Nepal
Netherlands
New Zealand
Nigeria
North Macedonia
Norway
Panama
Peru
Philippines
Poland
Portugal
Qatar
Romania
Saudi Arabia
Serbia
SE Stockholm
SE Streaming Optimized
Singapore
Slovakia
Slovenia
South Africa
South Korea
Sri Lanka
Switzerland
Taiwan
Turkey
UK London
UK Manchester
Ukraine
UK Southampton
UK Streaming Optimized
United Arab Emirates
Uruguay
Venezuela
Vietnam

**Comment by anorth2** [comment]
Actually this isn't resolved. There's an open issue on the proper gluetun repo: https://github.com/qdm12/gluetun/issues/2048#issuecomment-1918106565

Even using regions with port-forwarding enabled is giving connection refused on signature retrieval.
