### ISSUE TITLE
Docker-Compose for Private-internet-access needs modification

### ISSUE THREAD

**Issue by overlordian** [qdm12/gluetun-wiki#42]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/private-internet-access.md

### What's incorrect?

Docker-Compose section of the providers page for Private-internet-access does not work as is and should be modified.

 volumes:
      - gluetun:/gluetun
      
 Appears to be incorrect syntax for docker-compose does not work as is... suggest adding " ./ " by changing to:  

volumes:
     - ./gluetun:/gluetun

**Comment by Wobak** [comment]
You can actually do it with gluetun:/gluetun

You just have to declare the volume in the volumes section of the compose file

**Comment by overlordian** [comment]
Fair...and correct....
You can declare a glutun volume

I am more concerned with your documentation for people who don't know how to make this docker compse file work.  If none of your other provider documents declare volumes...I wouldn't expect people to think they need to declare one for PIA. Questions can come up of whether or not you need a volume for this particular provider...which in some cases that is true.  So does PIA, it doesn't seem so, no certs file needed.   This just looks like a typo from that perspective.  So if the intent is to have fully functional copyable documentation... Then I suggest changing your documentation.  Either add a declared volume or just make the change suggested...or just remove...

I am more concerned with people thinking your documentation is complete.  Please, if that is your intention update your documentation.  I would hate to have people get frustrated and not use your container if they can't debug on their own or start questioning their sanity against your intent through your documentation.

Thanks for the quick response last night.

**Comment by Wobak** [comment]
Absolutely no offense taken don't sweat it too much.

I think the good point about making the wiki as a separate repo is for easy management. You fork the repo, do the modification in the doc, commit it, and then do a PR explaining what you changed and what. 

Should be quite easily done :) Good luck !

**Comment by qdm12** [comment]
Hi @overlordian you are totally correct and thank you for reporting this! I even saw this a few minutes ago (I'm currently going through all wiki issues) and was wondering what the hell that bind mount declaration was 😄 And also thanks @Wobak for your input, it's always appreciated to have people commenting around on issues not of their own. Not all heroes wear capes 🦸 !

This is obviously fixed in afbb9dc4580544f0c7e18d811f79181ec38571fa
