### ISSUE TITLE
ERROR creating TUN device file node: file exists

### ISSUE THREAD

**Issue by sudarshan-uc** [qdm12/gluetun-wiki#55]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/errors/tun.md#creating-tun-device-file-node-file-exists

### What's missing?

Describe: container has been running properly for a while. Suddenly container is failing to start with above error. But already provided solution did not help.

Previous issues:
- https://github.com/qdm12/gluetun/issues/884
- https://github.com/qdm12/gluetun/issues/1537
- https://github.com/qdm12/gluetun/issues/1594

### System:
- RHEL 9: kernel: 5.14.0-362.18.1.el9_3.x86_64
- Podman + `crun` to manage gluetun.

Command to run the Gluetun container:
```
podman run -d --name=pia-vpn --ip 101.0.0.21 --pull newer --cap-add=NET_ADMIN --device=/dev/net/tun:/dev/net/tun -p 8888:8888/tcp -p 8388:8388/tcp -p 8388:8388/udp -v vpn-config:/gluetun -e HTTPPROXY=on -e VPN_SERVICE_PROVIDER="private internet access" -e OPENVPN_USER=Username -e OPENVPN_PASSWORD=Password -e SERVER_REGIONS="US East" -e PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=strong qmcgaw/gluetun:latest
```

### Error:
```
2024-03-12T17:28:00Z INFO [routing] default route found: interface eth0, gateway 10.88.0.1, assigned IP 10.88.0.21 and family v4
2024-03-12T17:28:00Z INFO [routing] deleting route for 0.0.0.0/0
2024-03-12T17:28:00Z ERROR creating TUN device file node: file exists
2024-03-12T17:28:00Z INFO Shutdown successful
```

### Investigation done:

- Running the container as `root`.
- Validated the correct module and kernel version
- rebooted system
- listed the loaded module: Noticed that the `tun` module was not getting loaded during the boot.

#### Validation:

```
# lsmod | grep tun   <--- returned no output
# ll /dev/net/tun
crw-rw-rw-. 1 root root 10, 200 Mar 11 00:00 /dev/net/tun
```

#### manually loaded the module:

```
# modprob tun
# lsmod | grep tun
tun                    73728  0
```

Post-loading, the container started correctly.

#### Solution: Load the module during boot:

```
echo 'tun' > /etc/modules-load.d/tun.conf
cat /etc/modules-load.d/tun.conf
tun
```

**Comment by qdm12** [comment]
Awesome detailed issue, thanks for the investigation and explanations! Closing this with #56 merged now.
