### ISSUE TITLE
Should be clearer that a wireguard conf file overrides environment variables, even when using openvpn.

### ISSUE THREAD

**Issue by jpcastberg** [qdm12/gluetun-wiki#67]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/wireguard.md

### What's misleading?

Heya - love gluetun, it's a cornerstone of my homelab!

I spent a bunch of time debugging why the port specified in my openvpn config was being changed to something else at runtime. Turns out, the wireguard conf at `/gluetun/wireguard/wg0.conf` from my previous setup was overriding the port - both in the openvpn config and the environment variable I had set for the port. This was confusing as I was expecting values from the wireguard config not to be used when I configured the container to use openvpn.

Ideally, the wireguard config's values would not be used if the user specifies use of openvpn - but for now, an extra line in the `/setup/options/wireguard.md` saying that the wireguard config's values take precedent even when using an openvpn config would be great. I'd be happy to open a PR for this.

Thank you!

**Comment by qdm12** [comment]
This was fixed a few days ago in 36c8da7ea7152d71ba62c5f1884784793d4facde 😉 And it could had been a wiki issue, but really it just doesn't make sense so it was fixed at the program level 😄
