### ISSUE TITLE
ERROR no iptables supported found: errors encountered are: iptables-nft: iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument (exit status 4)

### ISSUE THREAD

**Issue by Ikzy** [qdm12/gluetun-wiki#68]
Using the latest build (see log)
I'm getting an error regarding Iptables support. Is this a bug or something wrong in my config?  

 ERROR no iptables supported found: errors encountered are: iptables-nft: iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument (exit status 4); iptables: iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument (exit status 4)

attached the log. with the version. 

2024/05/02 15:56:23 | stdout | 2024-05-02T15:56:23+02:00 INFO Shutdown successful
-- | -- | --
2024/05/02 15:56:23 | stdout | 2024-05-02T15:56:23+02:00 ERROR no iptables supported found: errors encountered are: iptables-nft: iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument (exit status 4); iptables: iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument (exit status 4)
2024/05/02 15:56:23 | stdout | 2024-05-02T15:56:23+02:00 INFO [routing] local ipnet found: 172.18.0.0/16
2024/05/02 15:56:23 | stdout | 2024-05-02T15:56:23+02:00 INFO [routing] local ethernet link found: eth0
2024/05/02 15:56:23 | stdout | 2024-05-02T15:56:23+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4

2024/05/02 15:56:23 | stdout | Running version latest built on 2024-05-02T09:21:40.587Z (commit 6dd27e5)
-- | -- | --

kind regards,

Izzy

**Comment by conlethoc** [comment]
I changed from latest to 3.38.0 and it seemed to solve it

**Comment by Ikzy** [comment]
> I changed from latest to 3.38.0 and it seemed to solve it

yes! changing :latest  to :v3.38.0  works! let's not forget to return to latest to keep receiving updates later down the road.

thanks conlethoc

**Comment by LowHanger** [comment]
Same here, and solution (change to v3.38.0 vs latest) worked for me as well.

**Comment by cerealconyogurt** [comment]
Same here too, and same solution (moving from :latest to :v3.38.0)
