### ISSUE TITLE
Information about TAP Interface mode missing

### ISSUE THREAD

**Issue by CrazyVaclav** [qdm12/gluetun-wiki#69]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/openvpn.md

### What's missing?

Hi i cannot find any Information if the Network mode TAP is supported by the gluetun docker image.
As some openVPN Servers use Network Layer 2 TAP interfaces and when you try to connect you get an error but it is not clear if TAP Mode is supported by this project or not

**Comment by qdm12** [comment]
TAP is not supported, and I don't really want to support it for now, since most servers use TUN. Please open an issue on the Gluetun repository if you feel this would be a good addition. Thanks!
