### ISSUE TITLE
Port forwarding not supported for privatevpn

### ISSUE THREAD

**Issue by Silversurfer79** [qdm12/gluetun-wiki#77]
Hi All,

Any reason port forwaqrding isnt available or supported in Glutun for privatevpn?

They do support prot forwarding for the following locations: 
los-angeles-usa-allportfwd.ovpn  
new-york-usa-allportfwd.ovpn  
stockholm-sweden-allportfwd.ovpn

I have been using it with a [transmission-openvpn] container. 

This artcle also referse to them offering port forwarding. 
https://privatevpn.com/blog/guides/195/the-best-vpn-configuration-for-torrenting-fast-(and-safely)

Thanks for the help in advance.

**Comment by qdm12** [comment]
Documentation added in 1bab116a71bc97342a0eade304cc58d30998ea13

See https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md#allow-a-forwarded-port-through-the-firewall it was already documented 😉
