### ISSUE TITLE
WindScribe Incorrect Server Hostname

### ISSUE THREAD

**Issue by anup-khanal** [qdm12/gluetun-wiki#83]
### URL to the Wiki page

https://raw.githubusercontent.com/qdm12/gluetun/master/internal/storage/servers.json

### What's incorrect?

I was getting a constant health-check errors and the application shutdown with WindScribe VPN settings. I found out that the what we have in JSON file for hostnames and what we get from WindScribe is wrong. I am assuming gluten also uses the same JSON file.

Example:
The JSON file has "us-east-089.whiskergalaxy.com" as "Washington DC" but the WireGuard and OpenVPN settings we get from WindScribe shows: "was-324-wg.whiskergalaxy.com".

Almost all of the values have changed and needs an update.

**Comment by qdm12** [comment]
> Almost all of the values have changed and needs an update.

https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
