### ISSUE TITLE
Running 2 separate instances of gluetun with different regions

### ISSUE THREAD

**Issue by Dante2202** [qdm12/gluetun-wiki#84]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/multiple-gluetun.md

### What's missing?

The advanced faq states this can easily be done but there aren’t any docker compose examples of how to set up another container running gluetun if you already have one running to avoid any conflicting ports or issues. 

Would anyone who has accomplished this be able to provide an example of how to set this up please?

**Comment by EliotFR44** [comment]
Hi, 
Are you a proxy ?
Btw, you simply run your command twice, with different container names and different configurations.

**Comment by qdm12** [comment]
> if you already have one running to avoid any conflicting ports or issues.

This is kind of obvious, you cannot publish the same ports on your host for 2 different containers.
I don't believe an example is needed, and as @EliotFR44 said

> Btw, you simply run your command twice, with different container names and different configurations.

> My personal record is 600 glueten on the same hardware host.

Shit me, I didn't know you could push it that far 😄
