### ISSUE TITLE
SERVER_COUNTRIES has not description of what to fill it with

### ISSUE THREAD

**Issue by marshalleq** [qdm12/gluetun-wiki#85]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers

### What's missing?

There doesn't appear to be a list of options.  Even though I know what I want, your example is NETHERLANDS, the Surfshark file says nl-ams.  So for nz-akl the SERVER_COUNTRIES would be what?  NZ?  NEW ZEALAND?  NEW_ZEALAND?

I'm honestly not sure how this is supposed to work.  I assume I just put my openvpn file into surfshare and ignore this field?  What does it do?

**Comment by duderin0** [comment]
I just signed up with Surfshark recently, and was looking to use gluetun now too. Though I'm using wireguard and not OpenVPN like you.

I believe what you are looking for is on this wiki page: https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#list-of-vpn-servers
and the first few lines of output for surfshark show like this:

```
| Region | Country | City | Hostname | MultiHop | TCP | UDP |
| --- | --- | --- | --- | --- | --- | --- |
| Europe | Albania | Tirana | `al-tia.prod.surfshark.com` | ❌ | ✅ | ✅ |
| Europe | Albania | Tirana | `al-tia.prod.surfshark.com` | ❌ | ❌ | ✅ |
| Middle East and Africa | Algeria | Algiers | `dz-alg.prod.surfshark.com` | ❌ | ✅ | ✅ |
| Middle East and Africa | Algeria | Algiers | `dz-alg.prod.surfshark.com` | ❌ | ❌ | ✅ |
| Europe | Andorra | Andorra la Vella | `ad-leu.prod.surfshark.com` | ❌ | ✅ | ✅ |
| Europe | Andorra | Andorra la Vella | `ad-leu.prod.surfshark.com` | ❌ | ❌ | ✅ |
| The Americas | Argentina | Buenos Aires | `ar-bua.prod.surfshark.com` | ❌ | ✅ | ✅ |
| The Americas | Argentina | Buenos Aires | `ar-bua.prod.surfshark.com` | ❌ | ❌ | ✅ |
```
Oddly enough though, I'm having trouble having it respect any env variables I put in; Country is the only one that works. (haven't tried region but its too broad for me). City doesn't work, and Hostname doesn't either. I saw somewhere else to add the :51820 to the end of the hostname, but that also didn't work. Maybe OpenVPN will act different? You can always try it out, but I think you want the full city names like from the output above; so, `SERVER_COUNTRIES='New Zealand'`

If you want to use the OpenVPN config file, I did find a page for that but seems like it isn't recommended: https://github.com/qdm12/gluetun-wiki/blob/main/setup/openvpn-configuration-file.md#implicit-behavior

**Comment by qdm12** [comment]
@marshalleq Read the last section: https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/surfshark.md#servers

@duderin0 all these values in the table are used to filter servers built-in Gluetun (in the servers.json file), so it has to be an exact match.

> I'm having trouble having it respect any env variables I put in; Country is the only one that works.

Please create an issue on the gluetun repo (not the wiki) if this is the case. Maybe try updating your servers data to make sure this is not the case? Thanks!

**Comment by marshalleq** [comment]
I did read this last section already and re-reading it I still believe it doesn't say what to put.  What do you put for New Zealand?  What I'm asking is, so it has to be an exact match, where is the exact thing for New Zealand that I match it to?  I can't see it anywhere.
