### ISSUE TITLE
ProtonVPN features filters

### ISSUE THREAD

**Issue by blaisebrennan** [qdm12/gluetun-wiki#87]
### URL to the Wiki page

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md

### What's missing?

I see in the docs (https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md) that issue #1582 (https://github.com/qdm12/gluetun/issues/1582) adds support for filtering servers by feature. Can you let me know what the relevant environment variables should be set to in order to filter to P2P servers? FYI, I use Docker Compose.

Thanks!

**Comment by qdm12** [comment]
Done in 52c9b2ecf52e413eb4552345d7cffb41e6606806
